# netlify.toml at project_root/

[build]
  # IMPORTANT: Keep this line. It explicitly tells Netlify where your functions are.
  functions = "netlify/functions" 
  command = "echo 'Starting build...' && pwd && ls -la && echo 'Creating functions directory...' && mkdir -p netlify/functions && echo 'Files in root:' && find . -name '*.py' -type f && echo 'Copying files...' && cp *.py netlify/functions/ && echo 'Functions directory contents:' && ls -la netlify/functions/ && echo '.netlify: && cat .netlify' && echo 'Python' && python3 --version && echo 'Build complete.'"
  publish = "public" 

# --- FUNCTIONS CONFIGURATION ---

# Scheduled function configuration
[functions."wos_sondheim_alert"]
  schedule = "0 9 * * *"

# Environment variables for functions
[functions.environment]
  PYTHON_VERSION = "3.12"