# netlify.toml at project_root/

[build]
  # IMPORTANT: Keep this line. It explicitly tells Netlify where your functions are.
  # If you remove it, Netlify might not find them if the default isn't exactly 'netlify/functions'.
  functions = "netlify/functions" 
  command = "mkdir -p netlify/functions && cp config.py netlify/functions/"
  publish = "public" 

# --- FUNCTIONS CONFIGURATION ---

# We are REMOVING the global [functions] table entirely, 
# as it seems to conflict with [[functions]].
# Instead, we will define environment variables directly within each [[functions]] block.

[[functions]] 
  function = "wos_sondheim_alert"
  schedule = "0 9 * * *"          
  environment = { PYTHON_VERSION = "3.12" } 
