# netlify.toml at project_root/

[build]
  # IMPORTANT: Keep this line. It explicitly tells Netlify where your functions are.
  functions = "netlify/functions" 
  command = "mkdir -p netlify/functions && cp config.py netlify/functions/"
  publish = "public" 

# --- FUNCTIONS CONFIGURATION ---

# Scheduled function configuration
[functions."wos_sondheim_alert"]
  schedule = "0 9 * * *"

# Environment variables for functions
[functions.environment]
  PYTHON_VERSION = "3.12"