[build]
  functions = "netlify/functions"

[functions]
  python_version = "3.12.3"

[[functions]]
  schedule = "0 9 * * *"  # Run daily at 9 AM UTC
  name = "wos_sondheim_alert"

[build.environment]
  PYTHONPATH = "/opt/buildhome/repo"

# Optional: If you want to override environment variables
# [context.production.environment]
#   MAX_VENUES = "3"
#   SEARCH_RADIUS_MILES = "50"